# Generated by Django 3.1 on 2020-11-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('utils', '0001_initial'),
        ('sendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sending_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sendings.sending'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_id',
            field=models.ManyToManyField(to='utils.State'),
        ),
    ]
