# Generated by Django 3.1 on 2020-11-14 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20201114_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
