# Generated by Django 3.1 on 2020-11-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendings', '0001_initial'),
        ('sales', '0002_invoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sending_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sendings.sending'),
        ),
    ]
