# Generated by Django 3.1 on 2020-11-14 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_invoice_sending_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
