# Generated by Django 3.1 on 2020-11-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
