# Generated by Django 3.1 on 2020-11-14 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_invoice_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
