# Generated by Django 3.1 on 2020-11-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20201114_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='adress',
            new_name='address',
        ),
    ]
