# Generated by Django 3.1 on 2020-11-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_code',
            new_name='code',
        ),
    ]
